/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidoConcluidoRouteImport } from './routes/pedido-concluido'
import { Route as IndexRouteImport } from './routes/index'

const PedidoConcluidoRoute = PedidoConcluidoRouteImport.update({
  id: '/pedido-concluido',
  path: '/pedido-concluido',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pedido-concluido': typeof PedidoConcluidoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pedido-concluido': typeof PedidoConcluidoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pedido-concluido': typeof PedidoConcluidoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pedido-concluido'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pedido-concluido'
  id: '__root__' | '/' | '/pedido-concluido'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PedidoConcluidoRoute: typeof PedidoConcluidoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedido-concluido': {
      id: '/pedido-concluido'
      path: '/pedido-concluido'
      fullPath: '/pedido-concluido'
      preLoaderRoute: typeof PedidoConcluidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PedidoConcluidoRoute: PedidoConcluidoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
